version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    image: eu.gcr.io/endless-bonus-370920/frontend:latest 
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    image: eu.gcr.io/endless-bonus-370920/backend:latest 
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=mongodb+srv://cloud-edge-backend:logmigpaa@cluster0.lrrx168.mongodb.net/?retryWrites=true&w=majority
      - MONGO_DB_NAME=GCP
      - REDIS_URI=10.125.198.195:6379
      #not in bouild, used to keep track of values